name: web_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.2.1
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  get_it: ^7.2.0
  camera: 0.8.1+7
  image_size_getter: ^2.1.2
  gallery_saver: ^2.3.2
  mask_text_input_formatter: ^2.0.0
  pinch_zoom: ^1.0.0
  another_flushbar: ^1.12.29
  intl: ^0.17.0
  shimmer: ^2.0.0
  http: ^0.13.5
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.2
  timelines: ^0.1.0
  responsive_framework: ^1.0.0
  brasil_fields: ^1.9.0
  pinput: ^2.2.16
  camera_web: ^0.3.0+1
  cpf_cnpj_validator: ^2.0.0
  flutter_svg: ^1.1.6
  device_info_plus: ^8.0.0
  flutter_countdown_timer: ^4.1.0
  custom_pop_up_menu: ^1.2.4
  flutter_pagination: ^0.0.8
  connectivity_plus: ^3.0.2
  hive: ^2.2.3
  path_provider: ^2.0.12
  flutter_dotenv: ^5.0.2
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.3
  line_icons: ^2.0.1
  bottom_navy_bar: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  searchfield: ^0.7.5
  calendar_view: ^1.0.2
  syncfusion_flutter_calendar: ^20.4.52
  percent_indicator: ^4.2.2
  chat_bubbles: ^1.4.0
  flutter_masked_text2: ^0.9.1
  convex_bottom_bar: ^3.2.0
  circular_bottom_navigation: ^2.3.0
  step_progress_indicator: ^1.0.2
  confetti: ^0.7.0
  # google_sign_in: ^6.0.2
  # flutter_facebook_auth: ^5.0.8
  # firebase_core: "2.8.0"
  # firebase_analytics: "10.1.5"
  # firebase_crashlytics: "3.0.16"
  # firebase_auth: ^4.3.0
  flutter_phosphor_icons: ^0.0.1+6
  share_plus: ^6.3.1
  contacts_service: ^0.6.3
  darq: ^1.2.1
  # permission_handler: ^10.2.0
  flutter_local_notifications: ^13.0.0
  # firebase_messaging: ^14.3.0
  url_launcher: ^6.1.10
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^3.0.3
  go_router: ^6.5.5
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env.development
    - .env.production
